### PR TITLE
convert to github action builds + create helm test image

### PR DESCRIPTION
**Pull request by nieuwsma**
### Summary and Scope

Gets rid of jenkinsfile, rpm build
builds via github actions
creates a CT test image
s/arti.dev.cray.com/artifactory.algol60.net
upgrade alpine versions

### Issues and Related PRs

* merge with https://github.com/Cray-HPE/hms-bss/pull/44

### Testing

Tested on:

* mug

deployed the chart, copied the images into the registry
ran helm test
it worked.  See comments for outputs

Were the install/upgrade based validation checks/tests run?(goss tests/install-validation doc)
Were continuous integration tests run? Y
Was an Upgrade tested?                 Y
Was a Downgrade tested?                Y

### CODE REVIEW

**Comment by nieuwsma** [comment]
```
ncn-m001:~/anieuwsma # kubectl -n services logs cray-hms-bss-test-smoke-9w4fq smoke
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 15000 after 1 ms: Connection refused
Waiting for Sidecar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
HTTP/1.1 200 OK
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
content-type: text/html; charset=UTF-8
cache-control: no-cache, max-age=0
x-content-type-options: nosniff
date: Thu, 03 Mar 2022 22:50:21 GMT
server: envoy
transfer-encoding: chunked

Sidecar available
Running smoke tests...
2022-03-03 22:50:21,946 suite_name: BSS-smoke-tests
2022-03-03 22:50:21,946 file_path: smoke.json
2022-03-03 22:50:21,946 Running BSS-smoke-tests...
2022-03-03 22:50:21,946 default_url: http://cray-bss
2022-03-03 22:50:21,946 override_url: http://cray-bss
2022-03-03 22:50:21,946 configured_url: http://cray-bss/
2022-03-03 22:50:21,947 Testing {"path": "boot/v1/service/version", "expected_status_code": 200, "method": "GET", "body": null, "headers": {}, "url": "http://cray-bss/boot/v1/service/version"}
2022-03-03 22:50:21,967 Starting new HTTP connection (1): cray-bss:80
2022-03-03 22:50:22,040 http://cray-bss:80 "GET /boot/v1/service/version HTTP/1.1" 200 25
2022-03-03 22:50:22,042 Testing {"path": "boot/v1/service/status", "expected_status_code": 200, "method": "GET", "body": null, "headers": {}, "url": "http://cray-bss/boot/v1/service/status"}
2022-03-03 22:50:22,075 Starting new HTTP connection (1): cray-bss:80
2022-03-03 22:50:22,094 http://cray-bss:80 "GET /boot/v1/service/status HTTP/1.1" 200 25
2022-03-03 22:50:22,095 Testing {"path": "boot/v1/bootparameters", "expected_status_code": 200, "method": "GET", "body": null, "headers": {}, "url": "http://cray-bss/boot/v1/bootparameters"}
2022-03-03 22:50:22,122 Starting new HTTP connection (1): cray-bss:80
2022-03-03 22:50:22,283 http://cray-bss:80 "GET /boot/v1/bootparameters HTTP/1.1" 200 None
2022-03-03 22:50:22,285 Testing {"path": "boot/v1/dumpstate", "expected_status_code": 200, "method": "GET", "body": null, "headers": {}, "url": "http://cray-bss/boot/v1/dumpstate"}
2022-03-03 22:50:22,316 Starting new HTTP connection (1): cray-bss:80
2022-03-03 22:50:22,542 http://cray-bss:80 "GET /boot/v1/dumpstate HTTP/1.1" 200 None
2022-03-03 22:50:22,545 Testing {"path": "boot/v1/bootscript?nid=0", "expected_status_code": 200, "method": "GET", "body": null, "headers": {}, "url": "http://cray-bss/boot/v1/bootscript?nid=0"}
2022-03-03 22:50:22,577 Starting new HTTP connection (1): cray-bss:80
2022-03-03 22:50:22,721 http://cray-bss:80 "GET /boot/v1/bootscript?nid=0 HTTP/1.1" 200 122
2022-03-03 22:50:22,723 Testing {"path": "boot/v1/hosts", "expected_status_code": 200, "method": "GET", "body": null, "headers": {}, "url": "http://cray-bss/boot/v1/hosts"}
2022-03-03 22:50:22,758 Starting new HTTP connection (1): cray-bss:80
2022-03-03 22:50:22,867 http://cray-bss:80 "GET /boot/v1/hosts HTTP/1.1" 200 None
2022-03-03 22:50:22,869 MAIN_ERRORS = 0
2022-03-03 22:50:22,869 PASS: BSS-smoke-tests
2022-03-03 22:50:22,869 passed!
2022-03-03 22:50:22,869 PASS: BSS-smoke-tests passed!
ncn-m001:~/anieuwsma #
```

**Comment by nieuwsma** [comment]
```
ncn-m001:~/anieuwsma/bss # kubectl -n services logs cray-hms-bss-test-functional-rbqqb functional
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 15000 after 1 ms: Connection refused
Waiting for Sidecar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
HTTP/1.1 200 OK
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
content-type: text/html; charset=UTF-8
cache-control: no-cache, max-age=0
x-content-type-options: nosniff
date: Thu, 03 Mar 2022 22:51:28 GMT
server: envoy
transfer-encoding: chunked

Sidecar available
Running functional tests...
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.1.2, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /src/app, configfile: pytest.ini
plugins: tap-3.3, tavern-1.12.2
collecting ... collected 8 items

test_bootscript.tavern.yaml::Verify the dumpstate resource PASSED        [ 12%]
test_bootscript.tavern.yaml::Verify the bootscript resource PASSED       [ 25%]
test_bootscript.tavern.yaml::Verify the bootscript service gracefully handles invalid nids for the bootscript resource[9999999999999999999999999999] PASSED [ 37%]
test_bootscript.tavern.yaml::Verify the bootscript service gracefully handles invalid nids for the bootscript resource[one] PASSED [ 50%]
test_bootscript.tavern.yaml::Verify the bootscript service gracefully handles invalid nids for the bootscript resource[-1] PASSED [ 62%]
test_bootscript.tavern.yaml::Verify the bootscript service gracefully handles invalid nids for the bootscript resource[*] PASSED [ 75%]
test_bootscript.tavern.yaml::Verify the bootscript service gracefully handles invalid nids for the bootscript resource[] PASSED [ 87%]
test_bootscript.tavern.yaml::Verify the bootscript service gracefully handles invalid query paramters for the bootscript resource PASSED [100%]

============================== 8 passed in 7.03s ===============================
2022-03-03 22:51:36,090 PASS
```

**Comment by nieuwsma** [comment]
You can see it spun up all the containers it was supposed to:

```
cray-bss-784b589cb8-46t4x                                         2/2     Running     0          4m21s
cray-bss-784b589cb8-qqzht                                         2/2     Running     0          3m41s
cray-bss-784b589cb8-vm7pl                                         2/2     Running     0          4m20s
cray-bss-etcd-ml98rthkwt                                          1/1     Running     0          36d
cray-bss-etcd-n4nggh59s2                                          1/1     Running     0          36d
cray-bss-etcd-vd26nw8v2j                                          1/1     Running     0          36d
cray-bss-wait-for-etcd-2-r4kw9                                    0/1     Completed   0          4m21s
cray-hms-bss-test-functional-rbqqb                                1/2     NotReady    0          55s
cray-hms-bss-test-smoke-9w4fq                                     0/2     Completed   0          2m13s
```

**Comment by nieuwsma** [comment]
```ncn-m001:~/anieuwsma/bss # helm test -n services cray-hms-bss
NAME: cray-hms-bss
LAST DEPLOYED: Thu Mar  3 22:47:54 2022
NAMESPACE: services
STATUS: deployed
REVISION: 2
TEST SUITE:     cray-hms-bss-test-functional
Last Started:   Thu Mar  3 22:51:21 2022
Last Completed: Thu Mar  3 22:52:39 2022
Phase:          Succeeded
TEST SUITE:     cray-hms-bss-test-smoke
Last Started:   Thu Mar  3 22:50:03 2022
Last Completed: Thu Mar  3 22:51:21 2022
Phase:          Succeeded```

**Review by mpkelly-hpe — APPROVED** [review]

**Comment by nieuwsma** [comment]
> @nieuwsma can you remind me where the smoke tests and functional tests were moved to? ie bss_smoke_test_ncn-smoke.sh and test_BootScriptByCLI.py
@phalseth-hpe -> the functional and smoke tests are at : test/ct/{functional ... smoke}
The CLI tests have been removed. We will not do CLI tests and will we not create tests the depend on access to kubectl.  These are API tests strictly.

**Pull request merged**
