### PR TITLE
Changed to search in the cached state manager data

### PR DESCRIPTION
**Pull request by shunr-hpe**
When getting bootparameters by a name, mac, or nid it was getting all
the data in the etcd database. Reading all this data is slow when
there are a lot of bootparameters.

This commit changes it to search in the smd data which is cached in
memory. As a result it only looks up a few things in etcd.

Jira: CASMHMS-4540

### Summary and Scope

HTTP calls like following are made often in some install scripts.
/boot/v1/bootparameters?name=x3001c0s31b0n0

This call is slow when there are a lot of boot parameters. The reason it is slow is because bss retrieves all of it's etcd data. This changes it to instead only query for specific etcd key/values and instead it searches the state manager data that it has in memory.

### Issues and Related PRs

* Resolves CASMHMS-4540

### Testing

Tested on wasp. Ran the smoke and integration tests. Compared the results of the following calls before and after the changes.
```
curl -s -X GET -H "Authorization: Bearer ${TOKEN}" 'https://api-gw-service-nmn.local/apis/bss/boot/v1/bootparameters'
curl -s -X GET -H "Authorization: Bearer ${TOKEN}" 'https://api-gw-service-nmn.local/apis/bss/boot/v1/dumpstate'
curl -s -X GET -H "Authorization: Bearer ${TOKEN}" 'https://api-gw-service-nmn.local/apis/bss/boot/v1/bootparameters?name=x3000c0s10b2n0'
curl -s -X GET -H "Authorization: Bearer ${TOKEN}" 'https://api-gw-service-nmn.local/apis/bss/boot/v1/bootparameters?nid=100004'
curl -s -X GET -H "Authorization: Bearer ${TOKEN}" 'https://api-gw-service-nmn.local/apis/bss/boot/v1/bootparameters?mac=98:03:9b:aa:97:20'
curl -s -X GET -H "Authorization: Bearer ${TOKEN}" 'https://api-gw-service-nmn.local/apis/bss/boot/v1/bootparameters?name=x3000c0s10b2n0,x3000c0s1b0n0&mac=48:df:37:b2:3c:0f,48:df:37:b2:3c:1f,junk,98:03:9b:aa:97:20&nid=100004,42'

# in smd but not boot parameters
curl -s -X GET -H "Authorization: Bearer ${TOKEN}" 'https://api-gw-service-nmn.local/apis/bss/boot/v1/bootparameters?name=x3000c0s10b4n0'

# does not exist in bss and smd
curl -s -X GET -H "Authorization: Bearer ${TOKEN}" 'https://api-gw-service-nmn.local/apis/bss/boot/v1/bootparameters?name=x3000c0s10b4n1'
```

Tested in docker compose environment. Verified that the results are the same before and after these changes.
http get:

- /boot/v1/bootparameters?nid=100020
- /boot/v1/bootparameters?mac=ff:ff:ff:ff:ff:ff
- /boot/v1/bootparameters?mac=b8:59:9f:d9:9d:68,b8:59:9f:d9:9d:69,b8:59:9f:d9:9d:b1
- /boot/v1/bootparameters?name=x4499c0s42b0n0,x3000c0s36b0n0,x3000c0s36b0n0junk,x3000c0s36b0&mac=a4:bf:01:28:9b:17,junk&nid=1,49169408,999999
- /boot/v1/bootparameters?name=x3001c0s31b0n0
- DELETE /boot/v1/bootparameters -d '{ "hosts" : [ "x3001c0s31b0n0" ] }; GET /boot/v1/bootparameters?name=x3001c0s31b0n0; GET /boot/v1/bootparameters?nid=100016'
- Tested fqdn names by changing the code to inject them into the cached smd data.

Were the install/upgrade based validation checks/tests run?(goss tests/install-validation doc)
Were continuous integration tests run? Y
Was an Upgrade tested?                 Y
Was a Downgrade tested?                Y
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?

### Risks and Mitigations

A different method of searching is being used. There could be differences. To mitigate I tested multiple different cases.

### CODE REVIEW

**Comment by shunr-hpe** [comment]
Log from testing on wasp:
[hms-bss-casmhms-4540-bootparameters.md](https://github.com/Cray-HPE/hms-bss/files/7720410/hms-bss-casmhms-4540-bootparameters.md)

**Comment by shunr-hpe** [comment]
The difference in performance is 2.5 seconds per requests before my changes and less than .1 seconds after. This was tested with 522 boot parameters, using docker compose on a linux vm.

before changes
```
time curl -s -X GET 'localhost:27778/boot/v1/bootparameters?name=x3000c0s10b2n0' > /dev/null

real    0m2.693s
user    0m0.005s
sys     0m0.006s
```
after changes
```
time curl -s -X GET 'localhost:27778/boot/v1/bootparameters?name=x3000c0s10b2n0' > /dev/null

real    0m0.018s
user    0m0.007s
sys     0m0.005s
```

**Review by mjendrysik-hpe — APPROVED** [review]

**Comment by mjendrysik-hpe** [comment]
Just curious, did you determine the performance improvement with your new algorithm? =

**Comment by shunr-hpe** [comment]
> Just curious, did you determine the performance improvement with your new algorithm?

When testing with shandy data in a docker compose environment on my vm I got the following results:

- /boot/v1/bootparameters?nid=1386
  before changes: 1m10.293s
  after changes: 0m0.689s
- /boot/v1/bootparameters?mac=00:40:a6:83:02:4c
  before changes: 1m12.706s
  after changes: 0m0.148s
- /boot/v1/bootparameters?name=x3000c0s9b0n0
  before changes: 1m16.334s
  after changes: 0m0.055s

**Review by rsjostrand-hpe — APPROVED** [review]

**Comment by nieuwsma** [comment]
Going to go with #42 instead.

**Pull request closed without merging**
